[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]  
name="exercises-chapter-3"
version = "0.1.0"


[tool.hatch.build.targets.wheel]
packages = ["polynomials","shape"]
